name: SubsKun
options:
  minimumXcodeGenVersion: 2.44.0
  developmentLanguage: ja
  deploymentTarget:
    iOS: '17.0'
packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 8.0.0
settings:
  base:
    SWIFT_VERSION: '6.0'
    DEVELOPMENT_TEAM: SW4S6FR5L9
    CURRENT_PROJECT_VERSION: 5
    MARKETING_VERSION: 1.0
targets:
  SubsKun:
    type: application
    platform: iOS
    sources:
      - path: SubscriptionTracker
      - path: SubscriptionTracker/App/GoogleService-Info.plist
        buildPhase: resources
      - path: SubscriptionTracker/App/AuthKey.p8
        buildPhase: resources
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.uechikohei.subskun
        PRODUCT_NAME: SubsKun
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: SubscriptionTracker/App/Info.plist
        CODE_SIGN_ENTITLEMENTS: SubscriptionTracker/App/SubsKun.entitlements
        GOOGLE_CLIENT_ID: '618727271553-duekfg7vpuik5sqf0d5h5ihjcpiqpjrs.apps.googleusercontent.com'
        GOOGLE_REVERSED_CLIENT_ID: 'com.googleusercontent.apps.618727271553-duekfg7vpuik5sqf0d5h5ihjcpiqpjrs'
        APPLE_KEY_ID: 'BYZ8HLV9UW'
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: '1'
    scheme:
      gatherCoverageData: true
      testTargets:
        - SubsKunTests
  SubsKunTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: SubscriptionTrackerTests
    dependencies:
      - target: SubsKun
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.uechikohei.subskunTests
        GENERATE_INFOPLIST_FILE: YES
